version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-book
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata:/data/db
    networks:
      - docker-network


volumes:
  dbdata:

networks:
  docker-network:
    driver: bridge